// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: cubicles.proto

package cubiclespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Capacity      int32                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_cubicles_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_cubicles_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_cubicles_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Metadata) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type Reservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      string                 `protobuf:"bytes,1,opt,name=recordId,proto3" json:"recordId,omitempty"`
	RecordType    string                 `protobuf:"bytes,2,opt,name=recordType,proto3" json:"recordType,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end,proto3" json:"end,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reservation) Reset() {
	*x = Reservation{}
	mi := &file_cubicles_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reservation) ProtoMessage() {}

func (x *Reservation) ProtoReflect() protoreflect.Message {
	mi := &file_cubicles_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reservation.ProtoReflect.Descriptor instead.
func (*Reservation) Descriptor() ([]byte, []int) {
	return file_cubicles_proto_rawDescGZIP(), []int{1}
}

func (x *Reservation) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *Reservation) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

func (x *Reservation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Reservation) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Reservation) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *Reservation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Availability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvailableNow  bool                   `protobuf:"varint,1,opt,name=availableNow,proto3" json:"availableNow,omitempty"`
	NextAvailable *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=nextAvailable,proto3" json:"nextAvailable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Availability) Reset() {
	*x = Availability{}
	mi := &file_cubicles_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Availability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Availability) ProtoMessage() {}

func (x *Availability) ProtoReflect() protoreflect.Message {
	mi := &file_cubicles_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Availability.ProtoReflect.Descriptor instead.
func (*Availability) Descriptor() ([]byte, []int) {
	return file_cubicles_proto_rawDescGZIP(), []int{2}
}

func (x *Availability) GetAvailableNow() bool {
	if x != nil {
		return x.AvailableNow
	}
	return false
}

func (x *Availability) GetNextAvailable() *timestamppb.Timestamp {
	if x != nil {
		return x.NextAvailable
	}
	return nil
}

type CubicleDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Reservation   *Availability          `protobuf:"bytes,2,opt,name=reservation,proto3" json:"reservation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CubicleDetails) Reset() {
	*x = CubicleDetails{}
	mi := &file_cubicles_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CubicleDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CubicleDetails) ProtoMessage() {}

func (x *CubicleDetails) ProtoReflect() protoreflect.Message {
	mi := &file_cubicles_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CubicleDetails.ProtoReflect.Descriptor instead.
func (*CubicleDetails) Descriptor() ([]byte, []int) {
	return file_cubicles_proto_rawDescGZIP(), []int{3}
}

func (x *CubicleDetails) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CubicleDetails) GetReservation() *Availability {
	if x != nil {
		return x.Reservation
	}
	return nil
}

type GetMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CubicleId     string                 `protobuf:"bytes,1,opt,name=cubicleId,proto3" json:"cubicleId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_cubicles_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cubicles_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_cubicles_proto_rawDescGZIP(), []int{4}
}

func (x *GetMetadataRequest) GetCubicleId() string {
	if x != nil {
		return x.CubicleId
	}
	return ""
}

type GetMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataResponse) Reset() {
	*x = GetMetadataResponse{}
	mi := &file_cubicles_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataResponse) ProtoMessage() {}

func (x *GetMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cubicles_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetMetadataResponse) Descriptor() ([]byte, []int) {
	return file_cubicles_proto_rawDescGZIP(), []int{5}
}

func (x *GetMetadataResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMetadataRequest) Reset() {
	*x = CreateMetadataRequest{}
	mi := &file_cubicles_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMetadataRequest) ProtoMessage() {}

func (x *CreateMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cubicles_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMetadataRequest.ProtoReflect.Descriptor instead.
func (*CreateMetadataRequest) Descriptor() ([]byte, []int) {
	return file_cubicles_proto_rawDescGZIP(), []int{6}
}

func (x *CreateMetadataRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CubicleId     string                 `protobuf:"bytes,1,opt,name=cubicleId,proto3" json:"cubicleId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMetadataResponse) Reset() {
	*x = CreateMetadataResponse{}
	mi := &file_cubicles_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMetadataResponse) ProtoMessage() {}

func (x *CreateMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cubicles_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMetadataResponse.ProtoReflect.Descriptor instead.
func (*CreateMetadataResponse) Descriptor() ([]byte, []int) {
	return file_cubicles_proto_rawDescGZIP(), []int{7}
}

func (x *CreateMetadataResponse) GetCubicleId() string {
	if x != nil {
		return x.CubicleId
	}
	return ""
}

type CheckAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CubicleId     string                 `protobuf:"bytes,1,opt,name=cubicleId,proto3" json:"cubicleId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityRequest) Reset() {
	*x = CheckAvailabilityRequest{}
	mi := &file_cubicles_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityRequest) ProtoMessage() {}

func (x *CheckAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cubicles_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_cubicles_proto_rawDescGZIP(), []int{8}
}

func (x *CheckAvailabilityRequest) GetCubicleId() string {
	if x != nil {
		return x.CubicleId
	}
	return ""
}

type CheckAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Availability  *Availability          `protobuf:"bytes,1,opt,name=availability,proto3" json:"availability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityResponse) Reset() {
	*x = CheckAvailabilityResponse{}
	mi := &file_cubicles_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityResponse) ProtoMessage() {}

func (x *CheckAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cubicles_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_cubicles_proto_rawDescGZIP(), []int{9}
}

func (x *CheckAvailabilityResponse) GetAvailability() *Availability {
	if x != nil {
		return x.Availability
	}
	return nil
}

type GetCubicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CubicleId     string                 `protobuf:"bytes,1,opt,name=cubicleId,proto3" json:"cubicleId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCubicleRequest) Reset() {
	*x = GetCubicleRequest{}
	mi := &file_cubicles_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCubicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCubicleRequest) ProtoMessage() {}

func (x *GetCubicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cubicles_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCubicleRequest.ProtoReflect.Descriptor instead.
func (*GetCubicleRequest) Descriptor() ([]byte, []int) {
	return file_cubicles_proto_rawDescGZIP(), []int{10}
}

func (x *GetCubicleRequest) GetCubicleId() string {
	if x != nil {
		return x.CubicleId
	}
	return ""
}

type GetCubicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *CubicleDetails        `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCubicleResponse) Reset() {
	*x = GetCubicleResponse{}
	mi := &file_cubicles_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCubicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCubicleResponse) ProtoMessage() {}

func (x *GetCubicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cubicles_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCubicleResponse.ProtoReflect.Descriptor instead.
func (*GetCubicleResponse) Descriptor() ([]byte, []int) {
	return file_cubicles_proto_rawDescGZIP(), []int{11}
}

func (x *GetCubicleResponse) GetDetails() *CubicleDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

// Opcionales para manejo de reservaciones
type CreateReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservation   *Reservation           `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationRequest) Reset() {
	*x = CreateReservationRequest{}
	mi := &file_cubicles_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationRequest) ProtoMessage() {}

func (x *CreateReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cubicles_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationRequest.ProtoReflect.Descriptor instead.
func (*CreateReservationRequest) Descriptor() ([]byte, []int) {
	return file_cubicles_proto_rawDescGZIP(), []int{12}
}

func (x *CreateReservationRequest) GetReservation() *Reservation {
	if x != nil {
		return x.Reservation
	}
	return nil
}

type CreateReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      string                 `protobuf:"bytes,1,opt,name=recordId,proto3" json:"recordId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationResponse) Reset() {
	*x = CreateReservationResponse{}
	mi := &file_cubicles_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationResponse) ProtoMessage() {}

func (x *CreateReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cubicles_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationResponse.ProtoReflect.Descriptor instead.
func (*CreateReservationResponse) Descriptor() ([]byte, []int) {
	return file_cubicles_proto_rawDescGZIP(), []int{13}
}

func (x *CreateReservationResponse) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

type CancelReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      string                 `protobuf:"bytes,1,opt,name=recordId,proto3" json:"recordId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReservationRequest) Reset() {
	*x = CancelReservationRequest{}
	mi := &file_cubicles_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationRequest) ProtoMessage() {}

func (x *CancelReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cubicles_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationRequest.ProtoReflect.Descriptor instead.
func (*CancelReservationRequest) Descriptor() ([]byte, []int) {
	return file_cubicles_proto_rawDescGZIP(), []int{14}
}

func (x *CancelReservationRequest) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

type CancelReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReservationResponse) Reset() {
	*x = CancelReservationResponse{}
	mi := &file_cubicles_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationResponse) ProtoMessage() {}

func (x *CancelReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cubicles_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationResponse.ProtoReflect.Descriptor instead.
func (*CancelReservationResponse) Descriptor() ([]byte, []int) {
	return file_cubicles_proto_rawDescGZIP(), []int{15}
}

func (x *CancelReservationResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_cubicles_proto protoreflect.FileDescriptor

const file_cubicles_proto_rawDesc = "" +
	"\n" +
	"\x0ecubicles.proto\x12\bcubicles\x1a\x1fgoogle/protobuf/timestamp.proto\"f\n" +
	"\bMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x05R\bcapacity\"\xd9\x01\n" +
	"\vReservation\x12\x1a\n" +
	"\brecordId\x18\x01 \x01(\tR\brecordId\x12\x1e\n" +
	"\n" +
	"recordType\x18\x02 \x01(\tR\n" +
	"recordType\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\tR\x06userId\x120\n" +
	"\x05start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"t\n" +
	"\fAvailability\x12\"\n" +
	"\favailableNow\x18\x01 \x01(\bR\favailableNow\x12@\n" +
	"\rnextAvailable\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\rnextAvailable\"z\n" +
	"\x0eCubicleDetails\x12.\n" +
	"\bmetadata\x18\x01 \x01(\v2\x12.cubicles.MetadataR\bmetadata\x128\n" +
	"\vreservation\x18\x02 \x01(\v2\x16.cubicles.AvailabilityR\vreservation\"2\n" +
	"\x12GetMetadataRequest\x12\x1c\n" +
	"\tcubicleId\x18\x01 \x01(\tR\tcubicleId\"E\n" +
	"\x13GetMetadataResponse\x12.\n" +
	"\bmetadata\x18\x01 \x01(\v2\x12.cubicles.MetadataR\bmetadata\"G\n" +
	"\x15CreateMetadataRequest\x12.\n" +
	"\bmetadata\x18\x01 \x01(\v2\x12.cubicles.MetadataR\bmetadata\"6\n" +
	"\x16CreateMetadataResponse\x12\x1c\n" +
	"\tcubicleId\x18\x01 \x01(\tR\tcubicleId\"8\n" +
	"\x18CheckAvailabilityRequest\x12\x1c\n" +
	"\tcubicleId\x18\x01 \x01(\tR\tcubicleId\"W\n" +
	"\x19CheckAvailabilityResponse\x12:\n" +
	"\favailability\x18\x01 \x01(\v2\x16.cubicles.AvailabilityR\favailability\"1\n" +
	"\x11GetCubicleRequest\x12\x1c\n" +
	"\tcubicleId\x18\x01 \x01(\tR\tcubicleId\"H\n" +
	"\x12GetCubicleResponse\x122\n" +
	"\adetails\x18\x01 \x01(\v2\x18.cubicles.CubicleDetailsR\adetails\"S\n" +
	"\x18CreateReservationRequest\x127\n" +
	"\vreservation\x18\x01 \x01(\v2\x15.cubicles.ReservationR\vreservation\"7\n" +
	"\x19CreateReservationResponse\x12\x1a\n" +
	"\brecordId\x18\x01 \x01(\tR\brecordId\"6\n" +
	"\x18CancelReservationRequest\x12\x1a\n" +
	"\brecordId\x18\x01 \x01(\tR\brecordId\"+\n" +
	"\x19CancelReservationResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xb2\x01\n" +
	"\x0fMetadataService\x12J\n" +
	"\vGetMetadata\x12\x1c.cubicles.GetMetadataRequest\x1a\x1d.cubicles.GetMetadataResponse\x12S\n" +
	"\x0eCreateMetadata\x12\x1f.cubicles.CreateMetadataRequest\x1a .cubicles.CreateMetadataResponse2\xae\x02\n" +
	"\x12ReservationService\x12\\\n" +
	"\x11CheckAvailability\x12\".cubicles.CheckAvailabilityRequest\x1a#.cubicles.CheckAvailabilityResponse\x12\\\n" +
	"\x11CreateReservation\x12\".cubicles.CreateReservationRequest\x1a#.cubicles.CreateReservationResponse\x12\\\n" +
	"\x11CancelReservation\x12\".cubicles.CancelReservationRequest\x1a#.cubicles.CancelReservationResponse2Y\n" +
	"\x0eCubicleService\x12G\n" +
	"\n" +
	"GetCubicle\x12\x1b.cubicles.GetCubicleRequest\x1a\x1c.cubicles.GetCubicleResponseB\"Z cubiculosup.com/proto;cubiclespbb\x06proto3"

var (
	file_cubicles_proto_rawDescOnce sync.Once
	file_cubicles_proto_rawDescData []byte
)

func file_cubicles_proto_rawDescGZIP() []byte {
	file_cubicles_proto_rawDescOnce.Do(func() {
		file_cubicles_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cubicles_proto_rawDesc), len(file_cubicles_proto_rawDesc)))
	})
	return file_cubicles_proto_rawDescData
}

var file_cubicles_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_cubicles_proto_goTypes = []any{
	(*Metadata)(nil),                  // 0: cubicles.Metadata
	(*Reservation)(nil),               // 1: cubicles.Reservation
	(*Availability)(nil),              // 2: cubicles.Availability
	(*CubicleDetails)(nil),            // 3: cubicles.CubicleDetails
	(*GetMetadataRequest)(nil),        // 4: cubicles.GetMetadataRequest
	(*GetMetadataResponse)(nil),       // 5: cubicles.GetMetadataResponse
	(*CreateMetadataRequest)(nil),     // 6: cubicles.CreateMetadataRequest
	(*CreateMetadataResponse)(nil),    // 7: cubicles.CreateMetadataResponse
	(*CheckAvailabilityRequest)(nil),  // 8: cubicles.CheckAvailabilityRequest
	(*CheckAvailabilityResponse)(nil), // 9: cubicles.CheckAvailabilityResponse
	(*GetCubicleRequest)(nil),         // 10: cubicles.GetCubicleRequest
	(*GetCubicleResponse)(nil),        // 11: cubicles.GetCubicleResponse
	(*CreateReservationRequest)(nil),  // 12: cubicles.CreateReservationRequest
	(*CreateReservationResponse)(nil), // 13: cubicles.CreateReservationResponse
	(*CancelReservationRequest)(nil),  // 14: cubicles.CancelReservationRequest
	(*CancelReservationResponse)(nil), // 15: cubicles.CancelReservationResponse
	(*timestamppb.Timestamp)(nil),     // 16: google.protobuf.Timestamp
}
var file_cubicles_proto_depIdxs = []int32{
	16, // 0: cubicles.Reservation.start:type_name -> google.protobuf.Timestamp
	16, // 1: cubicles.Reservation.end:type_name -> google.protobuf.Timestamp
	16, // 2: cubicles.Availability.nextAvailable:type_name -> google.protobuf.Timestamp
	0,  // 3: cubicles.CubicleDetails.metadata:type_name -> cubicles.Metadata
	2,  // 4: cubicles.CubicleDetails.reservation:type_name -> cubicles.Availability
	0,  // 5: cubicles.GetMetadataResponse.metadata:type_name -> cubicles.Metadata
	0,  // 6: cubicles.CreateMetadataRequest.metadata:type_name -> cubicles.Metadata
	2,  // 7: cubicles.CheckAvailabilityResponse.availability:type_name -> cubicles.Availability
	3,  // 8: cubicles.GetCubicleResponse.details:type_name -> cubicles.CubicleDetails
	1,  // 9: cubicles.CreateReservationRequest.reservation:type_name -> cubicles.Reservation
	4,  // 10: cubicles.MetadataService.GetMetadata:input_type -> cubicles.GetMetadataRequest
	6,  // 11: cubicles.MetadataService.CreateMetadata:input_type -> cubicles.CreateMetadataRequest
	8,  // 12: cubicles.ReservationService.CheckAvailability:input_type -> cubicles.CheckAvailabilityRequest
	12, // 13: cubicles.ReservationService.CreateReservation:input_type -> cubicles.CreateReservationRequest
	14, // 14: cubicles.ReservationService.CancelReservation:input_type -> cubicles.CancelReservationRequest
	10, // 15: cubicles.CubicleService.GetCubicle:input_type -> cubicles.GetCubicleRequest
	5,  // 16: cubicles.MetadataService.GetMetadata:output_type -> cubicles.GetMetadataResponse
	7,  // 17: cubicles.MetadataService.CreateMetadata:output_type -> cubicles.CreateMetadataResponse
	9,  // 18: cubicles.ReservationService.CheckAvailability:output_type -> cubicles.CheckAvailabilityResponse
	13, // 19: cubicles.ReservationService.CreateReservation:output_type -> cubicles.CreateReservationResponse
	15, // 20: cubicles.ReservationService.CancelReservation:output_type -> cubicles.CancelReservationResponse
	11, // 21: cubicles.CubicleService.GetCubicle:output_type -> cubicles.GetCubicleResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_cubicles_proto_init() }
func file_cubicles_proto_init() {
	if File_cubicles_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cubicles_proto_rawDesc), len(file_cubicles_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_cubicles_proto_goTypes,
		DependencyIndexes: file_cubicles_proto_depIdxs,
		MessageInfos:      file_cubicles_proto_msgTypes,
	}.Build()
	File_cubicles_proto = out.File
	file_cubicles_proto_goTypes = nil
	file_cubicles_proto_depIdxs = nil
}
